### ISSUE TITLE
badge updates

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/hole2-mdakit#12]
- [ ] LGTM badge no longer working – remove
- [ ] change docs badge to point to https://www.mdanalysis.org/hole2-mdakit/
- [ ] also codecov badge (see #6 )

**Comment by orbeckst** [comment]
While editing README, also change the title to hole2-mdakit instead of mdakithole2, right?

**Comment by OmkarBorhade98** [comment]
Hi @orbeckst, I would like to work on this issue. Can you please let me know what to do with codecov batch? Since it's no longer working, can we remove it?

**Comment by orbeckst** [comment]
The codecov badge needs to be fixed. 

You can submit a PR. @ianmkenney shoupd be able to review it.

**Comment by ianmkenney** [comment]
I think I just need to activate it in the codecov dashboard. Should be a fast fix. I will look at it soon. It might only be fixable by someone with admin.

**Comment by OmkarBorhade98** [comment]
Alright then, I will submit a PR for changes other than codecov :)
