### ISSUE TITLE
create conda-forge package

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/hole2-mdakit#34]
We should have a conda-forge package of this kit. This is especially useful on Linux/macOS where we can pull in the hole2 package as a dependency.

Once we have a conda package, we need to update the installation instructions #25 .

**Comment by lilyminium** [comment]
Up here: https://github.com/conda-forge/staged-recipes/pull/25166 anyone else want to be a maintainer? (Can also add after the fact)

**Comment by IAlibay** [comment]
I think we agreed on the rule of two for CF & PyPi. I.e. a minimum of two coredev maintainers. Given I currently have to do a lot of patch deployments I volunteer myself for access, although you would still need a second coredev.

**Comment by lilyminium** [comment]
Thanks @IAlibay, could you please comment on the PR to that effect too?

**Comment by IAlibay** [comment]
@lilyminium I think you have to add me to the recipe? At least it feels weird to agree to be a maintainer without it.

**Comment by lilyminium** [comment]
ok, added now

**Comment by IAlibay** [comment]
Still need another coredev maintainer to have a rule of two - pinging @MDAnalysis/coredevs

**Comment by orbeckst** [comment]
I agree to be a maintainer on the recipe. - @orbeckstAm 1/30/24 um 18:43 schrieb Irfan Alibay ***@***.***>:﻿
Still need another coredev maintainer to have a rule of two - pinging @MDAnalysis/coredevs

**Comment by lilyminium** [comment]
Done! https://github.com/conda-forge/mdahole2-feedstock
