### ISSUE TITLE
PyPi package

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/hole2-mdakit#43]
Related to #34 

We don't have a pypi entry either.

Given that this kit can work with an optional HOLE2 install, I would suggest doing a pypi release anyways? My take here being that users can always install hole2 manually for the platforms where we can't have it available on conda-forge.

**Comment by orbeckst** [comment]
Really? Creating a package slipped through??? I could have sworn that @ianmkenney made one but perhaps I am confusing it with the drama to get hole2 onto cf.

**Comment by IAlibay** [comment]
As far as I can tell there are no mdahole2 or mdakit-hole2 packages on pypi unfortunately.

**Comment by orbeckst** [comment]
yes, I believe you! There are _many_ packages when you search for "hole" so having an easily findable name would be good.

**Comment by lilyminium** [comment]
Up now: https://pypi.org/project/mdahole2/

**Comment by orbeckst** [comment]
Hooray!
