### ISSUE TITLE
What should the package name be?

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/hole2-mdakit#47]
## Expected behavior ##

The package name should reflect the name of the repo?

## Actual behavior ##

Right now the package is named as "mdahole2" instead of "hole2-mdakit". This means that an install using pip would be `pip install mdahole2` instead of `pip install hole2-mdakit`.

What is the intended package name?

**Comment by orbeckst** [comment]
I don't think we agreed on a fixed naming convention. waterdynamics is waterdynamics throughout, ENCORE is mdaencore, PathSimAnalysis is pathsimanalysis. 

Given that we have neither PyPi #43 nor conda-forge #34 packages, we do have an opportunity to change the package name.

I don't have any strong preferences. @lilyminium you're officially in charge here so I am happy to go along with your choice.

**Comment by lilyminium** [comment]
I'm happy to stick with mdahole2 unless anyone has any strong preferences otherwise, especially since that's similar-ish to mdaencore. We could rename the repo if that's confusing to people.

**Comment by lilyminium** [comment]
Discussed in a meeting and consensus was to stick with `mdahole2`, renaming the repo if necessary. Thanks @IAlibay for raising this point!
