### ISSUE TITLE
Redeploy 0.4.0

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/hole2-mdakit#51]
Tagging @lilyminium 

Looks like the release deployment didn't go through - I suspect because the anticipated OIDC bits weren't added on the pypi side of things.

**Comment by lilyminium** [comment]
No, it's because I am a silly and didn't change the repo name properly 🤦‍♀️ fixing now.

**Comment by IAlibay** [comment]
I've updated all the CI repo names in #52 - probably worth merging that in before next deployment.

**Comment by lilyminium** [comment]
Ok, deployment looks like it's working now. https://pypi.org/project/mdahole2/
