### ISSUE TITLE
codecov badge no longer working

### ISSUE THREAD

**Issue by ianmkenney** [MDAnalysis/hole2-mdakit#6]
Code coverage is no longer running properly since the transfer of repository ownership.

**Comment by orbeckst** [comment]
What needs to be done to fix this, @ianmkenney ?

**Comment by ianmkenney** [comment]
I think it's all on the codecov side, I might just have to log in and activate it. Can check later today.

**Comment by ianmkenney** [comment]
I just needed to replace the old token.
